# Generated by Django 2.1.7 on 2019-03-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='Some String', max_length=100),
        ),
    ]
